name: instagrampub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^2.0.1
  auto_direction: ^0.0.4+1
  cached_network_image: ^2.3.3
  camera: ^0.5.8+11
  cloud_firestore: ^0.12.9+4
  cupertino_icons: ^1.0.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.0.6
  flutter_image_compress: ^0.7.0
  geocoder: ^0.2.1
  giphy_get: ^1.0.1
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_downloader: ^0.20.1
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  ionicons: ^0.0.3
  liquid_swipe: ^1.5.0
  location: ^3.0.2
  path_provider: ^1.6.22
  provider: ^4.3.2+2
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  timeago: ^2.0.28
  url_launcher: ^5.7.10
  uuid: ^2.2.2
  badges: 
  # animator: 
  # auto_direction: 
  # badges: 
  # cached_network_image: 
  # #cloud_firestore: 
  # cupertino_icons:
  # firebase_analytics: ^5.0.2
  # firebase_auth: 
  # firebase_core: 
  # firebase_messaging: 
  # firebase_storage: 
  # flutter_image_compress: 
  # geocoder: 
  # giphy_get: 
  # http: 
  # image_cropper: 
  # #image_downloader:
  # image_picker: 
  # intl: 
  # ionicons: 
  # liquid_swipe: 
  # location: 
  # path_provider: 
  # provider: 
  # share: 
  # shared_preferences: 
  # timeago: 
  # url_launcher: 
  # uuid: 
  rename: 
  #video_player: 
  #cross_file: 
  #path:
  photo_manager: 
  storage_path: 
  flick_video_player:
  visibility_detector: 
  razorpay_flutter: 
  #firebase_dynamic_links: 
  #get_it:
  webview_flutter: 
  video_compress: 
  fluttertoast: 
  flare_flutter: ^3.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.19.3
  pin_code_fields: ^6.0.0
  pinch_zoom: ^0.1.0 
  scrolling_page_indicator: ^0.1.3
  flutter_staggered_grid_view: ^0.3.4
  day_night_switcher: ^0.2.0+1
  flutter_colorpicker: ^0.4.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Checkmark Animation.flr
    # - assets/images/user_placeholder.jpg
    # - assets/images/instagram_logo.png
    # - assets/images/shutter.png
    # - assets/images/switch_camera.png
    # - assets/images/gallery_button.png
    # - assets/images/verfiriedUserBadge.png
    - resources/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.otf
    - family: BeautifulPeople
      fonts:
        - asset: assets/fonts/BeautifulPeople.ttf
    - family: BeautyMountains
      fonts:
        - asset: assets/fonts/BeautyMountains.ttf
    - family: BiteChocolate
      fonts:
        - asset: assets/fonts/BiteChocolate.ttf
    - family: BlackberryJam
      fonts:
        - asset: assets/fonts/BlackberryJam.ttf
    - family: Tomatoes
      fonts:
        - asset: assets/fonts/Tomatoes.ttf
    - family: BunchBlossoms
      fonts:
        - asset: assets/fonts/BunchBlossoms.ttf
    - family: CinderelaRegular
      fonts:
        - asset: assets/fonts/CinderelaRegular.ttf
    - family: Countryside
      fonts:
        - asset: assets/fonts/Countryside.ttf
    - family: Halimun
      fonts:
        - asset: assets/fonts/Halimun.ttf
    - family: LemonJelly
      fonts:
        - asset: assets/fonts/LemonJelly.ttf
    - family: QuiteMagicalRegular
      fonts:
        - asset: assets/fonts/QuiteMagicalRegular.ttf
    - family: TropicalAsianDemoRegular
      fonts:
        - asset: assets/fonts/TropicalAsianDemoRegular.ttf
    - family: VeganStyle
      fonts:
        - asset: assets/fonts/VeganStyle.ttf
    - family: Gilroy
      fonts:
        - asset: resources/fonts/Gilroy-Medium.ttf
        - asset: resources/fonts/Gilroy-Bold.ttf
          weight: 700
